name: sampleproject
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  assets_audio_player: ^3.0.6
  sqflite: ^2.0.0+3
  audioplayers: ^0.20.1
  intl: ^0.18.1

  cupertino_icons: ^1.0.2
  flutter_sound: ^9.2.13
  image_picker: ^0.8.9
  permission_handler: ^10.3.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - image/
    - images/
    - voice/
    - assets/images/
    - assets/sounds/
  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplaySC-Black.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: Source Sans Pro
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.ttf

    - family: S S P
      fonts:
        - asset: assets/fonts/SourceSansPro-Black.otf
